export const joshData = {
  personal: {
    fullname: "Joshua Martin",
    email: "joshua.g.martin.email@gmail.com",
    phone: "(936) 697-3800",
    location: "Waupaca, WI, USA",
    portfolioName: "GitHub",
    portfolioLink: "https://github.com/joshuaGmartin",
  },
  education: [
    {
      id: crypto.randomUUID(),
      school: "Western Governors University",
      gradYear: "2025",
      currentStudent: true,
      location: "",
      degree: "Master of Science",
      major: "Computer Science",
      minor: false,
      concentration: "Computing Systems",
      gpa: false,
      gpaScale: false,
      awards: [],
      coursework: [
        "Emerging Computing Systems",
        "Formal Languages Overview",
        "Computer Architecture and Systems",
        "Applied Algorithms and Reasoning",
        "Unix and Linux",
        "Artificial Intelligence and Machine Learning Foundations",
        "Mobile and Ubiquitous Design",
        "Governance, Risk, and Compliance",
        "Software Architecture and Design",
        "Network Architecture and Cloud Computing",
      ],
    },
    {
      id: crypto.randomUUID(),
      school: "Sam Houston State University",
      gradYear: "2013",
      currentStudent: false,
      location: "Huntsville, TX",
      degree: "Bachelor of Science",
      major: "Physics",
      minor: "Mathematics",
      concentration: false,
      gpa: "3.9",
      gpaScale: "4.0",
      awards: ["Magna Cum Laude", "Dean's List"],
      coursework: [
        "Linear Algebra",
        "Calculus",
        "Statistics",
        "(Partial) Differential Equations",
        "Java",
        "Theoretical Physics",
        "Classical Mechanics",
        "Quantum Mechanics",
        "Electricity and Magnetism",
        "Special Relativity",
      ],
    },
  ],
  workExperience: [
    {
      id: crypto.randomUUID(),
      employer: "Freelance Web Development",
      totalTimeStart: "2024",
      totalTimeEnd: "Present",
      jobsInfo: [
        {
          id: crypto.randomUUID(),
          position: "Developer",
          timeStart: "2024",
          timeEnd: "Present",
          location: "Remote",
          duties: [
            "Solved web-based issues for clients, from API integration to front-end design",
            "Self-taught via The Odin Project; sought real-world freelance projects to grow skills",
          ],
          stack: [
            "JavaScript",
            "HTML/CSS",
            "Git/GitHub",
            "Linux/WSL (Ubuntu)",
            "VS Code",
            "WordPress",
            "PHP",
          ],
          keyResults: [],
        },
      ],
    },
    {
      id: crypto.randomUUID(),
      employer: "EquipmentShare",
      totalTimeStart: "2023",
      totalTimeEnd: "2025",
      jobsInfo: [
        {
          id: crypto.randomUUID(),
          position: "Bonds Manager",
          timeStart: "Feb 2024",
          timeEnd: "Jan 2025",
          location: "Remote",
          duties: [
            "Created and managed a working process for filing bond claims for all U.S. states for non-payment of equipment",
            "Leveraged my programming skills to automate my daily tasks (Excel).",
          ],
          stack: [],
          keyResults: [
            "Promoted due to my attention to detail, initiative, and teachability.",
          ],
        },
        {
          id: crypto.randomUUID(),
          position: "Lien Specialist",
          timeStart: "Nov 2023",
          timeEnd: "Feb 2024",
          location: "Remote",
          duties: [
            "Prior to my promotion to Bonds Manager, I researched (GIS), processed, and filed mechanic's liens on job sites with unpaid rental equipment for 30 states (plus Washington D.C.).",
          ],
          stack: [],
          keyResults: [],
        },
      ],
    },
    {
      id: crypto.randomUUID(),
      employer: "Baker Hughes",
      totalTimeStart: "2013",
      totalTimeEnd: "2016",
      jobsInfo: [
        {
          id: crypto.randomUUID(),
          position: "Microseismic Geophysicist",
          timeStart: "",
          timeEnd: "",
          location: "Houston, TX",
          duties: [
            "Analyzed, processed, and managed large microseismic datasets from hydraulic fracturing, mapping out the fracture locations in real-time for clients.",
            "Traveled to job sites across America and Saudi Arabia",
            "Worked closely with engineering to test/troubleshoot new Linux-based remote software.",
          ],
          stack: [],
          keyResults: [
            "Remote data analysis allowed for field-based/travel cost savings for all geoscientists.",
          ],
        },
      ],
    },
  ],
  skillsAndInt: {
    hardSkillsTech: [
      "Python/pandas",
      "Jupyter",
      "Data Science",
      "APIs",
      "Unit Testing (Jest)",
      "Webpack",
      "npm",
      "OOP",
      "Modular Programming",
      "Test Driven Development",
      "MS Excel",
      "MS Office",
      "Some React/Node",
      "Math",
      "Physics",
    ],
    hardSkillsOther: [
      "Ghostwriting",
      "Copywriting",
      "Business Analysis",
      "eCommerce",
      "Real Estate",
      "Music",
      "Teaching",
    ],
    softSkills: [
      "Communication",
      "Creative Problem Solving",
      "Friendly/Easy-work-with",
      "Genuine",
      "Analytical",
      "Quick",
      "Learner",
      "Self-motivated",
      "Methodical",
    ],
    interests: [
      "Family (wife and four kids)",
      "Guitar",
      "Painting",
      "Fiction Novels",
      "Writing",
      "Calisthenics",
      "Chaos Theory",
    ],
  },
};

export const resetData = {
  personal: {
    fullname: "",
    email: "",
    phone: "",
    location: "",
    portfolioName: "",
    portfolioLink: "",
  },
  education: [
    {
      id: "",
      school: "",
      gradYear: "",
      currentStudent: false,
      location: "",
      degree: "",
      major: "",
      minor: "",
      concentration: false,
      gpa: false,
      gpaScale: false,
      awards: [],
      coursework: [],
    },
  ],
  workExperience: [
    {
      id: "",
      employer: "",
      totalTimeStart: "",
      totalTimeEnd: "",
      jobsInfo: [
        {
          id: "",
          position: "",
          timeStart: "",
          timeEnd: "",
          location: "",
          duties: [],
          stack: [],
          keyResults: [],
        },
      ],
    },
  ],
  skillsAndInt: {
    hardSkillsTech: [],
    hardSkillsOther: [],
    softSkills: [],
    interests: [],
  },
};
